version: '2.4'

x-limits: &limits
    pids_limit: 1024
    cpu_shares: 256
    mem_limit: 512m
    logging:
        options:
            max-size: 10m
            max-file: '3'

services:
    shell:
        <<: *limits
        build:
            context: ./shell
            args:
                USERNAME: piggy
                PASSWORD: OinkPassword0ink
                SANDBOX_REPO: https://github.com/nategraf/wrastle
                CTF_FLAG: flag{straw_houses_can_barely_stand_the_breeze}
        image: naumachia/login.shell
        expose:
            - "23"
        cap_add:
            - NET_BIND_SERVICE
        networks:
            default:
                ipv4_address: 172.30.0.2

    client:
        <<: *limits
        build: ./client
        image: naumachia/login.client
        command: [python, /app/client.py]
        restart: unless-stopped
        environment:
            SHELL_USER: piggy
            SHELL_PASS: OinkPassword0ink
        networks:
            default:
                ipv4_address: 172.30.0.3

networks:
    default:
        driver: l2bridge
        ipam:
            driver: static
            config:
                - subnet: 172.30.0.0/28
