version: '2.4'

x-limits: &limits
    pids_limit: 1024
    cpu_shares: 256
    mem_limit: 512m
    logging:
        options:
            max-size: 10m
            max-file: '3'

services:
    auth:
        <<: *limits
        build: ./auth
        image: naumachia/recipe.auth
        env_file: chal.env
        expose:
            - "4505"
        networks:
            default:
                ipv4_address: 172.30.0.2
        mac_address: 2e:03:10:cf:b3:ea
        restart: unless-stopped

    ftp:
        <<: *limits
        build: ./ftp
        image: naumachia/recipe.ftp
        env_file: chal.env
        environment:
            AUTH_ADDR: auth
            AUTH_PORT: 4505
        cap_add:
            - NET_BIND_SERVICE
        expose:
            - "21"
        networks:
            default:
                ipv4_address: 172.30.0.3
        mac_address: 2e:e7:80:8c:0a:f8
        restart: unless-stopped

networks:
    default:
        driver: l2bridge
        ipam:
            driver: static
            config:
                - subnet: 172.30.0.0/28
