challenges:
    listen:
        port: 2000
        files:
            - listen/docker-compose.yml

    middle:
        port: 2001
        files:
            - middle/docker-compose.yml

    straw:
        port: 2002
        files:
            - straw/docker-compose.yml

    sticks:
        port: 2003
        files:
            - sticks/docker-compose.yml

    brick:
        port: 2004
        files:
            - brick/docker-compose.yml

    segal:
        port: 2005
        files:
            - segal/docker-compose.yml

# Rose need some work. It currently eats up too many resources and is poorly constructed.
#    rose:
#        port: 2006
#        files:
#            - rose/docker-compose.yml
#            - common/docker-compose.yml
        
    scraps:
        port: 2007
        files:
            - scraps/docker-compose.yml

    recipe:
        port: 2008
        files:
            - recipe/docker-compose.yml

    letter:
        port: 2009
        files:
            - letter/docker-compose.yml

    calculator:
        port: 2010
        files:
            - calculator/docker-compose.yml

    clock:
        port: 2011
        files:
            - clock/docker-compose.yml

    homework:
        port: 2012
        files:
            - homework/docker-compose.yml

    altf4:
        port: 2013
        files:
            - altf4/docker-compose.yml

    copper:
        port: 2014
        files:
            - copper/docker-compose.yml

    wordpress:
        port: 2015
        files:
            - wordpress/docker-compose.yml
