version: '2.4'

x-limits: &limits
    pids_limit: 1024
    cpu_shares: 256
    mem_limit: 512m
    logging:
        options:
            max-size: 10m
            max-file: '3'

services:
    catfacts:
        <<: *limits
        build: ./catfacts
        image: naumachia/segal.catfacts
        networks:
            default:
                aliases:
                    - "catfacts.naum"
                ipv4_address: 172.30.0.2
        expose: 
            - "443"
        env_file: chal.env
        environment:
            - PYTHONPATH=/app
        working_dir: /app
        command: ["gunicorn", "-c", "python:config", "catfacts:app"]
        restart: unless-stopped

    ntp:
        <<: *limits
        image: cturra/ntp:latest
        expose:
            - 123/udp
        environment:
            NTP_SERVERS: 127.127.1.1
        networks:
            default:
                aliases:
                    - "time.naum"
                ipv4_address: 172.30.0.3
        restart: unless-stopped

    client:
        <<: *limits
        build: ./client
        image: naumachia/segal.client
        env_file: chal.env
        command: [python, /app/client.py]
        restart: unless-stopped
        networks:
            default:
                ipv4_address: 172.30.0.4

networks:
    default:
        driver: l2bridge
        ipam:
            driver: static
            config:
                - subnet: 172.30.0.0/28
