version: '2.4'

x-limits: &limits
    pids_limit: 1024
    cpu_shares: 256
    mem_limit: 512m
    logging:
        options:
            max-size: 10m
            max-file: '3'

services:
    bob:
        <<: *limits
        build: ./bob
        image: naumachia/aes.bob
        restart: unless-stopped
        hostname: bob
        networks:
            default:
                ipv4_address: 172.30.0.2
        mac_address: 2e:45:99:c7:82:4b
        restart: unless-stopped

    alice:
        <<: *limits
        build: ./alice
        image: naumachia/aes.alice
        restart: unless-stopped
        hostname: alice
        depends_on:
            - bob
        networks:
            default:
                ipv4_address: 172.30.0.3
        mac_address: 2e:70:27:20:ac:ca
        restart: unless-stopped

networks:
    default:
        driver: l2bridge
        ipam:
            driver: static
            config:
                - subnet: 172.30.0.0/28
