version: '2.1'

services:
    shell:
        build:
            context: ./shell
            args:
                USERNAME: piggy
                PASSWORD: ShesABrickH0use
                NAUMOTP_SECRET: CPE7C5JFZEYRBDL6X25ISBOQK2PE2A54F3U3MQOX6IVNADWNXYEA
                SANDBOX_REPO: https://github.com/catdaddy97/catfacts.git
                CTF_FLAG: flag{brick_walls_dont_help_if_you_hold_the_door_open}
        image: naumachia/login-otp.shell
        networks:
            default:
                ipv4_address: 172.30.0.2
        expose:
            - "23"
        cap_add:
            - NET_BIND_SERVICE

    client:
        image: naumachia/login.client
        command: [python, /app/client.py]
        environment:
            NAUMOTP_SECRET: CPE7C5JFZEYRBDL6X25ISBOQK2PE2A54F3U3MQOX6IVNADWNXYEA
            SHELL_USER: piggy
            SHELL_PASS: ShesABrickH0use
        networks:
            default:
                ipv4_address: 172.30.0.3
        restart: unless-stopped

networks:
    default:
        driver: l2bridge
        ipam:
            driver: static
            config:
                - subnet: 172.30.0.0/28
