version: '2.4'

x-limits: &limits
    pids_limit: 1024
    cpu_shares: 256
    mem_limit: 512m
    logging:
        options:
            max-size: 10m
            max-file: '3'

services:
    shell:
        <<: *limits
        build:
            context: ./shell
            args:
                USERNAME: piggy
                PASSWORD: ShesABrickH0use
                NAUMOTP_SECRET: CPE7C5JFZEYRBDL6X25ISBOQK2PE2A54F3U3MQOX6IVNADWNXYEA
                SANDBOX_REPO: https://github.com/catdaddy97/catfacts.git
                CTF_FLAG: flag{brick_walls_dont_help_if_you_hold_the_door_open}
        image: naumachia/login-otp.shell
        networks:
            default:
                ipv4_address: 172.30.0.2
        mac_address: 2e:5d:42:06:0d:bc
        expose:
            - "23"
        cap_add:
            - NET_BIND_SERVICE

    client:
        <<: *limits
        image: naumachia/login.client
        command: [python, /app/client.py]
        environment:
            NAUMOTP_SECRET: CPE7C5JFZEYRBDL6X25ISBOQK2PE2A54F3U3MQOX6IVNADWNXYEA
            SHELL_USER: piggy
            SHELL_PASS: ShesABrickH0use
        networks:
            default:
                ipv4_address: 172.30.0.3
        mac_address: 2e:22:06:75:01:cf
        restart: unless-stopped

networks:
    default:
        driver: l2bridge
        ipam:
            driver: static
            config:
                - subnet: 172.30.0.0/28
