version: '2.4'

x-limits: &limits
    pids_limit: 1024
    cpu_shares: 256
    mem_limit: 512m
    logging:
        options:
            max-size: 10m
            max-file: '3'

services:
    arthur: &knight
        <<: *limits
        build: ./actor
        image: naumachia/listen.actor
        env_file: chal.env
        environment:
            CHARACTER: Arthur
        restart: unless-stopped
        networks:
            default:
                ipv4_address: 172.30.0.2
        mac_address: 2e:65:7e:3e:cc:e6

    bedevere:
        <<: *knight
        environment:
            CHARACTER: Bedevere
        networks:
            default:
                ipv4_address: 172.30.0.3
        mac_address: 2e:29:a2:e0:fe:f1

    robin:
        <<: *knight
        environment:
            CHARACTER: Robin
        networks:
            default:
                ipv4_address: 172.30.0.4
        mac_address: 2e:90:b9:24:c4:c6

    bridgekeeper:
        <<: *knight
        environment:
            CHARACTER: Bridgekeeper
        networks:
            default:
                ipv4_address: 172.30.0.5
        mac_address: 2e:94:12:b7:8f:a1

    lancelot:
        <<: *knight
        environment:
            CHARACTER: Lancelot
        networks:
            default:
                ipv4_address: 172.30.0.6
        mac_address: 2e:f4:71:c2:26:6c

    galahad:
        <<: *knight
        environment:
            CHARACTER: Galahad
        networks:
            default:
                ipv4_address: 172.30.0.7
        mac_address: 2e:e0:f7:04:95:a9

networks:
    default:
        driver: l2bridge
        ipam:
            driver: static
            config:
                - subnet: 172.30.0.0/28
