version: '2.1'

services:
    arthur: &knight
        build: ./actor
        image: naumachia/listen.actor
        env_file: chal.env
        environment:
            CHARACTER: Arthur
        restart: unless-stopped
        networks:
            default:
                ipv4_address: 172.30.0.2

    bedevere:
        <<: *knight
        environment:
            CHARACTER: Bedevere
        networks:
            default:
                ipv4_address: 172.30.0.3

    robin:
        <<: *knight
        environment:
            CHARACTER: Robin
        networks:
            default:
                ipv4_address: 172.30.0.4

    bridgekeeper:
        <<: *knight
        environment:
            CHARACTER: Bridgekeeper
        networks:
            default:
                ipv4_address: 172.30.0.5

    lancelot:
        <<: *knight
        environment:
            CHARACTER: Lancelot
        networks:
            default:
                ipv4_address: 172.30.0.6

    galahad:
        <<: *knight
        environment:
            CHARACTER: Galahad
        networks:
            default:
                ipv4_address: 172.30.0.7

networks:
    default:
        driver: l2bridge
        ipam:
            driver: static
            config:
                - subnet: 172.30.0.0/28
