version: '2.1'

services:
    mailserver:
        build: ./mailserver
        image: naumachia/letter.mailserver
        cap_add:
            - NET_BIND_SERVICE
        ports:
            - "25"
        networks:
            default:
                ipv4_address: 172.30.0.2
        restart: unless-stopped

    client:
        build: ./client
        image: naumachia/letter.client
        environment:
            SMTP_ADDR: mailserver
        env_file: chal.env
        networks:
            default:
                ipv4_address: 172.30.0.3
        restart: unless-stopped

networks:
    default:
        driver: l2bridge
        ipam:
            driver: static
            config:
                - subnet: 172.30.0.0/28
