version: '2.4'

x-limits: &limits
    pids_limit: 1024
    cpu_shares: 256
    mem_limit: 512m
    logging:
        options:
            max-size: 10m
            max-file: '3'

services:
    mailserver:
        <<: *limits
        build: ./mailserver
        image: naumachia/letter.mailserver
        cap_add:
            - NET_BIND_SERVICE
        ports:
            - "25"
        networks:
            default:
                ipv4_address: 172.30.0.2
        restart: unless-stopped

    client:
        <<: *limits
        build: ./client
        image: naumachia/letter.client
        environment:
            SMTP_ADDR: mailserver
        env_file: chal.env
        networks:
            default:
                ipv4_address: 172.30.0.3
        restart: unless-stopped

networks:
    default:
        driver: l2bridge
        ipam:
            driver: static
            config:
                - subnet: 172.30.0.0/28
