version: '2.4'

x-limits: &limits
    pids_limit: 1024
    cpu_shares: 256
    mem_limit: 512m
    logging:
        options:
            max-size: 10m
            max-file: '3'

services:
    shell:
        <<: *limits
        build:
            context: ./shell
            args:
                USERNAME: alice
                PASSWORD: "58318008"
                CTF_FLAG: flag{civilians_dont_need_weapons_grade_cryto}
        image: naumachia/calculator.shell
        cap_add:
            - NET_BIND_SERVICE
        networks:
            default:
                ipv4_address: 172.30.0.2
        restart: unless-stopped

    client:
        <<: *limits
        build: ./client
        image: naumachia/calculator.client
        environment:
            SHELL_USER: alice
            SHELL_PASS:  "58318008"
        networks:
            default:
                ipv4_address: 172.30.0.3
        restart: unless-stopped

networks:
    default:
        driver: l2bridge
        ipam:
            driver: static
            config:
                - subnet: 172.30.0.0/28
