version: '2.1'

services:
    router:
        hostname: router.shadow
        networks:
            default:
            hidden:
        << : &shadow
            image: naumachia/common.router
            sysctls:
                net.ipv4.ip_forward: 1
            volumes:
                - routes:/mnt/routes
            environment:
                ROUTE_SHARE: /mnt/routes
            cap_add:
                - NET_ADMIN
            restart: unless-stopped

    giulietta:
        hostname: rosedigiulietta.shadow
        dns: 127.0.0.40
        build: ./giulietta
        image: naumachia/rose.giulietta
        networks:
            hidden:
        env_file: chal.env
        restart: unless-stopped
        cap_add:
            - NET_BIND_SERVICE
        restart: unless-stopped

    giulietta-shadow:
        network_mode: service:giulietta
        << : *shadow

    admin:
        hostname: admin.shadow
        env_file: chal.env
        environment:
            HTTP_URL: http://rosedigiulietta.naum
            NAMESERVER: ns.shadow
        << : &bot
            dns: 127.0.0.40
            build: ./client
            image: naumachia/rose.client
            networks:
                hidden:
            restart: unless-stopped

    admin-shadow:
        network_mode: service:admin
        << : *shadow

    luca:
        hostname: luca.shadow
        environment:
            ROSE_USER: luca
            ROSE_PASS: aerosmith1
            HTTP_URL: http://rosedigiulietta.naum
            NAMESERVER: ns.shadow
        << : *bot

    luca-shadow:
        network_mode: service:luca
        << : *shadow

    moroder:
        hostname: moroder.shadow
        environment:
            ROSE_USER: moroder
            ROSE_PASS: mazda626
            HTTP_URL: http://rosedigiulietta.naum
            NAMESERVER: ns.shadow
        << : *bot

    moroder-shadow:
        network_mode: service:moroder
        << : *shadow

    ns:
        hostname: ns.shadow
        dns: 127.0.0.40
        build: ./ns
        image: naumachia/rose.ns
        networks:
            default:
        environment:
            - ZONE_DOMAIN=naum
            - ZONE_HOSTS=rosedigiulietta
        restart: unless-stopped

    ns-shadow:
        network_mode: service:ns
        << : *shadow

volumes:
    routes:

networks:
    default:
        internal: true
        ipam:
            driver: mini
    hidden:
        internal: true
        ipam:
            driver: mini
