version: '2.4'

x-limits: &limits
    pids_limit: 1024
    cpu_shares: 256
    mem_limit: 512m
    logging:
        options:
            max-size: 10m
            max-file: '3'

services:
    mysql:
        <<: *limits
        build: ./mysql
        image: naumachia/mysqlword
        hostname: mysqlword
        networks:
            default:
                ipv4_address: 172.30.0.2
        mac_address: 2e:31:9e:67:05:7e
        restart: unless-stopped

    apache:
        <<: *limits
        build: ./apache
        image: naumachia/apacheword
        hostname: apacheword
        depends_on:
            - mysql
        networks:
            default:
                ipv4_address: 172.30.0.3
        mac_address: 2e:c8:81:27:78:d9
        restart: unless-stopped


networks:
    default:
        driver: l2bridge
        ipam:
            driver: static
            config:
                - subnet: 172.30.0.0/28
