version: '2.1'

services:
    bob:
        build: ./bob
        image: naumachia/mitm.bob
        restart: unless-stopped
        networks:
            default:
                ipv4_address: 172.30.0.2
        environment:
            - CTF_FLAG=i_gOT_the_FeELIN_SoMEThinG_ainT_rIGHt

    alice:
        build: ./alice
        image: naumachia/mitm.alice
        restart: unless-stopped
        networks:
            default:
                ipv4_address: 172.30.0.3
        depends_on:
            - bob
        environment:
            - CTF_FLAG=i_gOT_the_FeELIN_SoMEThinG_ainT_rIGHt

networks:
    default:
        driver: l2bridge
        ipam:
            driver: static
            config:
                - subnet: 172.30.0.0/28
