version: '2.4'

x-limits: &limits
    pids_limit: 1024
    cpu_shares: 256
    mem_limit: 512m
    logging:
        options:
            max-size: 10m
            max-file: '3'

services:
    bob:
        <<: *limits
        build: ./bob
        image: naumachia/mitm.bob
        restart: unless-stopped
        networks:
            default:
                ipv4_address: 172.30.0.2
        environment:
            - CTF_FLAG=i_got_the_feelin_something_aint_right

    alice:
        <<: *limits
        build: ./alice
        image: naumachia/mitm.alice
        restart: unless-stopped
        networks:
            default:
                ipv4_address: 172.30.0.3
        depends_on:
            - bob
        environment:
            - CTF_FLAG=i_got_the_feelin_something_aint_right

networks:
    default:
        driver: l2bridge
        ipam:
            driver: static
            config:
                - subnet: 172.30.0.0/28
