version: '2.4'

x-limits: &limits
    pids_limit: 1024
    cpu_shares: 256
    mem_limit: 512m
    logging:
        options:
            max-size: 10m
            max-file: '3'

services:
    shell:
        <<: *limits
        build:
            context: ./shell
            args:
                USERNAME: alice
                PASSWORD: TickTockOnTheCl0ck
                NAUMOTP_SECRET: DQ6K6V3MNA5F2BIZK2FYVPNXOQMW5YECOZMP7QU7VW3UOOBK3VHQ
                CTF_FLAG: flag{alice_should_get_a_watch}
        image: naumachia/clock.shell
        networks:
            default:
                ipv4_address: 172.30.0.2
        mac_address: 2e:93:b4:c5:a2:9f
        expose:
            - "23"
        cap_add:
            - NET_BIND_SERVICE
        restart: unless-stopped

    client:
        <<: *limits
        build: ./client
        image: naumachia/clock.client
        environment:
            NAUMOTP_SECRET: DQ6K6V3MNA5F2BIZK2FYVPNXOQMW5YECOZMP7QU7VW3UOOBK3VHQ
            SHELL_USER: alice
            SHELL_PASS: TickTockOnTheCl0ck
        networks:
            default:
                ipv4_address: 172.30.0.3
        mac_address: 2e:6a:e1:09:d1:83
        restart: unless-stopped

networks:
    default:
        driver: l2bridge
        ipam:
            driver: static
            config:
                - subnet: 172.30.0.0/28
