version: '2.1'

services:
    bob:
        build: ./bob
        image: naumachia/middle-arpon.bob
        volumes:
            - arpon:/etc/arpon
        environment:
            - CTF_FLAG=MORe_ThAn_ONE_WAy_tO_sKin_A_cAT
        sysctls:
            net.ipv4.conf.eth0.arp_ignore: 8
            net.ipv4.conf.eth0.arp_accept: 0
        networks:
            default:
                ipv4_address: 172.30.0.2
        cap_add:
            - NET_ADMIN
            - NET_RAW

    alice:
        build: ./alice
        image: naumachia/middle-arpon.alice
        volumes:
            - arpon:/etc/arpon
        depends_on:
            - bob
        environment:
            - CTF_FLAG=MORe_ThAn_ONE_WAy_tO_sKin_A_cAT
        sysctls:
            net.ipv4.conf.eth0.arp_ignore: 8
            net.ipv4.conf.eth0.arp_accept: 0
        networks:
            default:
                ipv4_address: 172.30.0.3
        cap_add:
            - NET_ADMIN
            - NET_RAW

volumes:
    arpon:

networks:
    default:
        driver: l2bridge
        ipam:
            driver: static
            config:
                - subnet: 172.30.0.0/28
