version: '2.4'

x-limits: &limits
    pids_limit: 1024
    cpu_shares: 256
    mem_limit: 512m
    logging:
        options:
            max-size: 10m
            max-file: '3'

services:
    bob:
        <<: *limits
        build: ./bob
        image: naumachia/middle-arpon.bob
        volumes:
            - arpon:/etc/arpon
        environment:
            - CTF_FLAG=MORe_ThAn_ONE_WAy_tO_sKin_A_cAT
        sysctls:
            net.ipv4.conf.eth0.arp_ignore: 8
            net.ipv4.conf.eth0.arp_accept: 0
        networks:
            default:
                ipv4_address: 172.30.0.2
        mac_address: 2e:a5:08:0e:d9:a3
        cap_add:
            - NET_ADMIN
            - NET_RAW

    alice:
        <<: *limits
        build: ./alice
        image: naumachia/middle-arpon.alice
        volumes:
            - arpon:/etc/arpon
        depends_on:
            - bob
        environment:
            - CTF_FLAG=MORe_ThAn_ONE_WAy_tO_sKin_A_cAT
        sysctls:
            net.ipv4.conf.eth0.arp_ignore: 8
            net.ipv4.conf.eth0.arp_accept: 0
        networks:
            default:
                ipv4_address: 172.30.0.3
        mac_address: 2e:4a:58:b2:09:cb
        cap_add:
            - NET_ADMIN
            - NET_RAW

volumes:
    arpon:

networks:
    default:
        driver: l2bridge
        ipam:
            driver: static
            config:
                - subnet: 172.30.0.0/28
